/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { PublicKey } from "@metaplex-foundation/umi";
import {
  Serializer,
  bool,
  publicKey as publicKeySerializer,
  struct,
} from "@metaplex-foundation/umi/serializers";

export type MCollection = { verified: boolean; key: PublicKey };

export type MCollectionArgs = MCollection;

export function getMCollectionSerializer(): Serializer<
  MCollectionArgs,
  MCollection
> {
  return struct<MCollection>(
    [
      ["verified", bool()],
      ["key", publicKeySerializer()],
    ],
    { description: "MCollection" }
  ) as Serializer<MCollectionArgs, MCollection>;
}
