[features]
seeds = false
skip-lint = false
idl-gen = [
    "anchor-lang/idl-gen",
]
[programs.localnet]
dpl_protocol = "ywpMZZNG3Nx1Bu2deJCcNxzUUoWSm6YwN9r9jCF8art"
[programs.devnet]
dpl_protocol = "ywpMZZNG3Nx1Bu2deJCcNxzUUoWSm6YwN9r9jCF8art"
[programs.mainnet]
dpl_protocol = "artMnyJqNruhMEAY1aibPNgFu68camwPhJ2nJyMEwgr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../../keys/admfHT9j1e6fcNgyfUDyy1ZB6rfbdveVHEZShZr3rYL.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# utils
deploy-idl = "ts-node ./scripts/deployIdl.ts"
ipfs = "ts-node ./scripts/ipfs/index.ts"
kinobi = "ts-node ./scripts/kinobi.ts"

# token
create-token = "ts-node ./scripts/token/createToken.ts"
transfer-tokens = "ts-node ./scripts/token/transferTokens.ts"

# platform
get-platforms = "ts-node ./scripts/platform/getPlatforms.ts"
create-platform = "ts-node ./scripts/platform/createPlatform.ts"
create-platform-artist = "ts-node ./scripts/platform/createAndAddArtistMint.ts"
create-platform-user = "ts-node ./scripts/platform/createAndAddUserMint.ts"
add-supported-token-details = "ts-node ./scripts/platform/addSupportedTokenDetails.ts"
add-subscription-plan = "ts-node ./scripts/platform/addSubscriptionPlan.ts"
update-subscription-details = "ts-node ./scripts/platform/updateSubscriptionDetails.ts"

# artist
get-artists = "ts-node ./scripts/artist/getArtists.ts"
create-artist = "ts-node ./scripts/artist/createArtist.ts"

# collection
get-collections = "ts-node ./scripts/collection/getCollections.ts"
create-collection = "ts-node ./scripts/collection/createCollection.ts"

# artwork
get-artworks = "ts-node ./scripts/artwork/getArtworks.ts"
create-c-artwork = "ts-node ./scripts/artwork/createCArtwork.ts"
create-i-artwork = "ts-node ./scripts/artwork/createIArtwork.ts"
print-artwork = "ts-node ./scripts/artwork/printArtwork.ts"

# user
get-users = "ts-node ./scripts/user/getUsers.ts"
create-user = "ts-node ./scripts/user/createUser.ts"
subscribe = "ts-node ./scripts/user/subscribe.ts"
unsubscribe = "ts-node ./scripts/user/unsubscribe.ts"
renewal = "ts-node ./scripts/user/renewal.ts"
approve-renewal = "ts-node ./scripts/user/approveRenewal.ts"

# user: marketplace
get-lists = "ts-node ./scripts/user/getLists.ts"
list-subscription = "ts-node ./scripts/user/listSubscription.ts"
delist-subscription = "ts-node ./scripts/user/delistSubscription.ts"
sell-subscription = "ts-node ./scripts/user/sellSubscription.ts"
claim-subscription = "ts-node ./scripts/user/claimSubscription.ts"