/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { Serializer, scalarEnum } from '@metaplex-foundation/umi/serializers';

/** allowed durations (in weeks) */
export enum Duration {
  One,
  Four,
  Twelve,
  TwentySix,
  FiftyTwo,
}

export type DurationArgs = Duration;

export function getDurationSerializer(): Serializer<DurationArgs, Duration> {
  return scalarEnum<Duration>(Duration, {
    description: 'Duration',
  }) as Serializer<DurationArgs, Duration>;
}
