/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { Serializer, struct, u64 } from "@metaplex-foundation/umi/serializers";
import { UseMethod, UseMethodArgs, getUseMethodSerializer } from ".";

export type MUses = { useMethod: UseMethod; remaining: bigint; total: bigint };

export type MUsesArgs = {
  useMethod: UseMethodArgs;
  remaining: number | bigint;
  total: number | bigint;
};

export function getMUsesSerializer(): Serializer<MUsesArgs, MUses> {
  return struct<MUses>(
    [
      ["useMethod", getUseMethodSerializer()],
      ["remaining", u64()],
      ["total", u64()],
    ],
    { description: "MUses" }
  ) as Serializer<MUsesArgs, MUses>;
}
