/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Serializer,
  struct,
  u64,
  u8,
} from "@metaplex-foundation/umi/serializers";
import { Duration, DurationArgs, getDurationSerializer } from ".";

export type SubscriptionPlan = {
  /** plan id */
  id: number;
  /** duration (in week) */
  duration: Duration;
  /** subscription price for selected duration */
  price: bigint;
};

export type SubscriptionPlanArgs = {
  /** plan id */
  id: number;
  /** duration (in week) */
  duration: DurationArgs;
  /** subscription price for selected duration */
  price: number | bigint;
};

export function getSubscriptionPlanSerializer(): Serializer<
  SubscriptionPlanArgs,
  SubscriptionPlan
> {
  return struct<SubscriptionPlan>(
    [
      ["id", u8()],
      ["duration", getDurationSerializer()],
      ["price", u64()],
    ],
    { description: "SubscriptionPlan" }
  ) as Serializer<SubscriptionPlanArgs, SubscriptionPlan>;
}
