/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  publicKey,
  transactionBuilder,
} from "@metaplex-foundation/umi";
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from "@metaplex-foundation/umi/serializers";
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from "../shared";
import { PrintArgs, PrintArgsArgs, getPrintArgsSerializer } from "../types";

// Accounts.
export type PrintArtworkInstructionAccounts = {
  /** artwork account */
  artwork: PublicKey | Pda;
  /** collection account */
  collection?: PublicKey | Pda;
  /** artist account */
  artist: PublicKey | Pda;
  /** platform account */
  platform: PublicKey | Pda;
  authority?: Signer;
  masterMint: PublicKey | Pda;
  masterTokenAccount: PublicKey | Pda;
  masterMetadata: PublicKey | Pda;
  masterEdition: PublicKey | Pda;
  editionMetadata: PublicKey | Pda;
  edition: PublicKey | Pda;
  editionMint: Signer;
  owner: Signer;
  editionTokenAccount: PublicKey | Pda;
  editionMarkerPda: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  metadataTokenProgram: PublicKey | Pda;
  sysvarInstructions?: PublicKey | Pda;
  associatedTokenProgram: PublicKey | Pda;
};

// Data.
export type PrintArtworkInstructionData = {
  discriminator: Array<number>;
  printArgs: PrintArgs;
};

export type PrintArtworkInstructionDataArgs = { printArgs: PrintArgsArgs };

export function getPrintArtworkInstructionDataSerializer(): Serializer<
  PrintArtworkInstructionDataArgs,
  PrintArtworkInstructionData
> {
  return mapSerializer<
    PrintArtworkInstructionDataArgs,
    any,
    PrintArtworkInstructionData
  >(
    struct<PrintArtworkInstructionData>(
      [
        ["discriminator", array(u8(), { size: 8 })],
        ["printArgs", getPrintArgsSerializer()],
      ],
      { description: "PrintArtworkInstructionData" }
    ),
    (value) => ({
      ...value,
      discriminator: [138, 161, 98, 106, 219, 81, 45, 47],
    })
  ) as Serializer<PrintArtworkInstructionDataArgs, PrintArtworkInstructionData>;
}

// Args.
export type PrintArtworkInstructionArgs = PrintArtworkInstructionDataArgs;

// Instruction.
export function printArtwork(
  context: Pick<Context, "identity" | "programs">,
  input: PrintArtworkInstructionAccounts & PrintArtworkInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    "dplProtocol",
    "ywpMZZNG3Nx1Bu2deJCcNxzUUoWSm6YwN9r9jCF8art"
  );

  // Accounts.
  const resolvedAccounts: ResolvedAccountsWithIndices = {
    artwork: { index: 0, isWritable: false, value: input.artwork ?? null },
    collection: {
      index: 1,
      isWritable: false,
      value: input.collection ?? null,
    },
    artist: { index: 2, isWritable: false, value: input.artist ?? null },
    platform: { index: 3, isWritable: false, value: input.platform ?? null },
    authority: { index: 4, isWritable: true, value: input.authority ?? null },
    masterMint: {
      index: 5,
      isWritable: false,
      value: input.masterMint ?? null,
    },
    masterTokenAccount: {
      index: 6,
      isWritable: false,
      value: input.masterTokenAccount ?? null,
    },
    masterMetadata: {
      index: 7,
      isWritable: false,
      value: input.masterMetadata ?? null,
    },
    masterEdition: {
      index: 8,
      isWritable: true,
      value: input.masterEdition ?? null,
    },
    editionMetadata: {
      index: 9,
      isWritable: true,
      value: input.editionMetadata ?? null,
    },
    edition: { index: 10, isWritable: true, value: input.edition ?? null },
    editionMint: {
      index: 11,
      isWritable: true,
      value: input.editionMint ?? null,
    },
    owner: { index: 12, isWritable: false, value: input.owner ?? null },
    editionTokenAccount: {
      index: 13,
      isWritable: true,
      value: input.editionTokenAccount ?? null,
    },
    editionMarkerPda: {
      index: 14,
      isWritable: true,
      value: input.editionMarkerPda ?? null,
    },
    systemProgram: {
      index: 15,
      isWritable: false,
      value: input.systemProgram ?? null,
    },
    tokenProgram: {
      index: 16,
      isWritable: false,
      value: input.tokenProgram ?? null,
    },
    metadataTokenProgram: {
      index: 17,
      isWritable: false,
      value: input.metadataTokenProgram ?? null,
    },
    sysvarInstructions: {
      index: 18,
      isWritable: false,
      value: input.sysvarInstructions ?? null,
    },
    associatedTokenProgram: {
      index: 19,
      isWritable: false,
      value: input.associatedTokenProgram ?? null,
    },
  };

  // Arguments.
  const resolvedArgs: PrintArtworkInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.authority.value) {
    resolvedAccounts.authority.value = context.identity;
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      "splSystem",
      "11111111111111111111111111111111"
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      "splToken",
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }
  if (!resolvedAccounts.sysvarInstructions.value) {
    resolvedAccounts.sysvarInstructions.value = publicKey(
      "Sysvar1nstructions1111111111111111111111111"
    );
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    "programId",
    programId
  );

  // Data.
  const data = getPrintArtworkInstructionDataSerializer().serialize(
    resolvedArgs as PrintArtworkInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
