/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from "@metaplex-foundation/umi";
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from "@metaplex-foundation/umi/serializers";
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from "../shared";

// Accounts.
export type AddSupportedTokenDetailsInstructionAccounts = {
  /** platform account */
  platform: PublicKey | Pda;
  /** update authority */
  authority?: Signer;
  /** mint account of a token that platform wants to support */
  tokenMint: PublicKey | Pda;
  /** token account of respective mint given above */
  tokenAccount: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  associatedTokenProgram: PublicKey | Pda;
};

// Data.
export type AddSupportedTokenDetailsInstructionData = {
  discriminator: Array<number>;
};

export type AddSupportedTokenDetailsInstructionDataArgs = {};

export function getAddSupportedTokenDetailsInstructionDataSerializer(): Serializer<
  AddSupportedTokenDetailsInstructionDataArgs,
  AddSupportedTokenDetailsInstructionData
> {
  return mapSerializer<
    AddSupportedTokenDetailsInstructionDataArgs,
    any,
    AddSupportedTokenDetailsInstructionData
  >(
    struct<AddSupportedTokenDetailsInstructionData>(
      [["discriminator", array(u8(), { size: 8 })]],
      { description: "AddSupportedTokenDetailsInstructionData" }
    ),
    (value) => ({
      ...value,
      discriminator: [191, 74, 121, 27, 185, 134, 30, 141],
    })
  ) as Serializer<
    AddSupportedTokenDetailsInstructionDataArgs,
    AddSupportedTokenDetailsInstructionData
  >;
}

// Instruction.
export function addSupportedTokenDetails(
  context: Pick<Context, "identity" | "programs">,
  input: AddSupportedTokenDetailsInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    "dplProtocol",
    "ywpMZZNG3Nx1Bu2deJCcNxzUUoWSm6YwN9r9jCF8art"
  );

  // Accounts.
  const resolvedAccounts: ResolvedAccountsWithIndices = {
    platform: { index: 0, isWritable: true, value: input.platform ?? null },
    authority: { index: 1, isWritable: true, value: input.authority ?? null },
    tokenMint: { index: 2, isWritable: false, value: input.tokenMint ?? null },
    tokenAccount: {
      index: 3,
      isWritable: true,
      value: input.tokenAccount ?? null,
    },
    systemProgram: {
      index: 4,
      isWritable: false,
      value: input.systemProgram ?? null,
    },
    tokenProgram: {
      index: 5,
      isWritable: false,
      value: input.tokenProgram ?? null,
    },
    associatedTokenProgram: {
      index: 6,
      isWritable: false,
      value: input.associatedTokenProgram ?? null,
    },
  };

  // Default values.
  if (!resolvedAccounts.authority.value) {
    resolvedAccounts.authority.value = context.identity;
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      "splSystem",
      "11111111111111111111111111111111"
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      "splToken",
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    "programId",
    programId
  );

  // Data.
  const data = getAddSupportedTokenDetailsInstructionDataSerializer().serialize(
    {}
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
