/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  publicKey,
  transactionBuilder,
} from "@metaplex-foundation/umi";
import {
  Serializer,
  array,
  mapSerializer,
  string,
  struct,
  u8,
} from "@metaplex-foundation/umi/serializers";
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from "../shared";
import { AssetData, AssetDataArgs, getAssetDataSerializer } from "../types";

// Accounts.
export type CreatePlatformInstructionAccounts = {
  /** platform account */
  platform: PublicKey | Pda;
  authority?: Signer;
  mint: Signer;
  tokenAccount: PublicKey | Pda;
  metadata: PublicKey | Pda;
  masterEdition: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  metadataTokenProgram: PublicKey | Pda;
  sysvarInstructions?: PublicKey | Pda;
  associatedTokenProgram: PublicKey | Pda;
};

// Data.
export type CreatePlatformInstructionData = {
  discriminator: Array<number>;
  domain: string;
  assetData: AssetData;
};

export type CreatePlatformInstructionDataArgs = {
  domain: string;
  assetData: AssetDataArgs;
};

export function getCreatePlatformInstructionDataSerializer(): Serializer<
  CreatePlatformInstructionDataArgs,
  CreatePlatformInstructionData
> {
  return mapSerializer<
    CreatePlatformInstructionDataArgs,
    any,
    CreatePlatformInstructionData
  >(
    struct<CreatePlatformInstructionData>(
      [
        ["discriminator", array(u8(), { size: 8 })],
        ["domain", string()],
        ["assetData", getAssetDataSerializer()],
      ],
      { description: "CreatePlatformInstructionData" }
    ),
    (value) => ({
      ...value,
      discriminator: [159, 106, 44, 241, 53, 188, 123, 238],
    })
  ) as Serializer<
    CreatePlatformInstructionDataArgs,
    CreatePlatformInstructionData
  >;
}

// Args.
export type CreatePlatformInstructionArgs = CreatePlatformInstructionDataArgs;

// Instruction.
export function createPlatform(
  context: Pick<Context, "identity" | "programs">,
  input: CreatePlatformInstructionAccounts & CreatePlatformInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    "dplProtocol",
    "ywpMZZNG3Nx1Bu2deJCcNxzUUoWSm6YwN9r9jCF8art"
  );

  // Accounts.
  const resolvedAccounts: ResolvedAccountsWithIndices = {
    platform: { index: 0, isWritable: true, value: input.platform ?? null },
    authority: { index: 1, isWritable: true, value: input.authority ?? null },
    mint: { index: 2, isWritable: true, value: input.mint ?? null },
    tokenAccount: {
      index: 3,
      isWritable: true,
      value: input.tokenAccount ?? null,
    },
    metadata: { index: 4, isWritable: true, value: input.metadata ?? null },
    masterEdition: {
      index: 5,
      isWritable: true,
      value: input.masterEdition ?? null,
    },
    systemProgram: {
      index: 6,
      isWritable: false,
      value: input.systemProgram ?? null,
    },
    tokenProgram: {
      index: 7,
      isWritable: false,
      value: input.tokenProgram ?? null,
    },
    metadataTokenProgram: {
      index: 8,
      isWritable: false,
      value: input.metadataTokenProgram ?? null,
    },
    sysvarInstructions: {
      index: 9,
      isWritable: false,
      value: input.sysvarInstructions ?? null,
    },
    associatedTokenProgram: {
      index: 10,
      isWritable: false,
      value: input.associatedTokenProgram ?? null,
    },
  };

  // Arguments.
  const resolvedArgs: CreatePlatformInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.authority.value) {
    resolvedAccounts.authority.value = context.identity;
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      "splSystem",
      "11111111111111111111111111111111"
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      "splToken",
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }
  if (!resolvedAccounts.sysvarInstructions.value) {
    resolvedAccounts.sysvarInstructions.value = publicKey(
      "Sysvar1nstructions1111111111111111111111111"
    );
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    "programId",
    programId
  );

  // Data.
  const data = getCreatePlatformInstructionDataSerializer().serialize(
    resolvedArgs as CreatePlatformInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
