/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  publicKey,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  i64,
  mapSerializer,
  struct,
  u64,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';
import { AssetData, AssetDataArgs, getAssetDataSerializer } from '../types';

// Accounts.
export type ListSubscriptionInstructionAccounts = {
  /** list account */
  list: PublicKey | Pda;
  /** platform account */
  platform: PublicKey | Pda;
  /** user account */
  user: PublicKey | Pda;
  authority?: Signer;
  /** mint account of chosen token for payment */
  paymentMint: PublicKey | Pda;
  /** authority's token account of chosen mint */
  authorityTokenAccount: PublicKey | Pda;
  mint: Signer;
  tokenAccount: PublicKey | Pda;
  metadata: PublicKey | Pda;
  masterEdition: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  metadataTokenProgram: PublicKey | Pda;
  sysvarInstructions?: PublicKey | Pda;
  associatedTokenProgram: PublicKey | Pda;
};

// Data.
export type ListSubscriptionInstructionData = {
  discriminator: Array<number>;
  listingStartsAt: bigint;
  price: bigint;
  assetData: AssetData;
};

export type ListSubscriptionInstructionDataArgs = {
  listingStartsAt: number | bigint;
  price: number | bigint;
  assetData: AssetDataArgs;
};

export function getListSubscriptionInstructionDataSerializer(): Serializer<
  ListSubscriptionInstructionDataArgs,
  ListSubscriptionInstructionData
> {
  return mapSerializer<
    ListSubscriptionInstructionDataArgs,
    any,
    ListSubscriptionInstructionData
  >(
    struct<ListSubscriptionInstructionData>(
      [
        ['discriminator', array(u8(), { size: 8 })],
        ['listingStartsAt', i64()],
        ['price', u64()],
        ['assetData', getAssetDataSerializer()],
      ],
      { description: 'ListSubscriptionInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [144, 240, 138, 66, 12, 37, 255, 185],
    })
  ) as Serializer<
    ListSubscriptionInstructionDataArgs,
    ListSubscriptionInstructionData
  >;
}

// Args.
export type ListSubscriptionInstructionArgs =
  ListSubscriptionInstructionDataArgs;

// Instruction.
export function listSubscription(
  context: Pick<Context, 'identity' | 'programs'>,
  input: ListSubscriptionInstructionAccounts & ListSubscriptionInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'dplProtocol',
    'ywpMZZNG3Nx1Bu2deJCcNxzUUoWSm6YwN9r9jCF8art'
  );

  // Accounts.
  const resolvedAccounts: ResolvedAccountsWithIndices = {
    list: { index: 0, isWritable: true, value: input.list ?? null },
    platform: { index: 1, isWritable: false, value: input.platform ?? null },
    user: { index: 2, isWritable: false, value: input.user ?? null },
    authority: { index: 3, isWritable: true, value: input.authority ?? null },
    paymentMint: {
      index: 4,
      isWritable: false,
      value: input.paymentMint ?? null,
    },
    authorityTokenAccount: {
      index: 5,
      isWritable: true,
      value: input.authorityTokenAccount ?? null,
    },
    mint: { index: 6, isWritable: true, value: input.mint ?? null },
    tokenAccount: {
      index: 7,
      isWritable: true,
      value: input.tokenAccount ?? null,
    },
    metadata: { index: 8, isWritable: true, value: input.metadata ?? null },
    masterEdition: {
      index: 9,
      isWritable: true,
      value: input.masterEdition ?? null,
    },
    systemProgram: {
      index: 10,
      isWritable: false,
      value: input.systemProgram ?? null,
    },
    tokenProgram: {
      index: 11,
      isWritable: false,
      value: input.tokenProgram ?? null,
    },
    metadataTokenProgram: {
      index: 12,
      isWritable: false,
      value: input.metadataTokenProgram ?? null,
    },
    sysvarInstructions: {
      index: 13,
      isWritable: false,
      value: input.sysvarInstructions ?? null,
    },
    associatedTokenProgram: {
      index: 14,
      isWritable: false,
      value: input.associatedTokenProgram ?? null,
    },
  };

  // Arguments.
  const resolvedArgs: ListSubscriptionInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.authority.value) {
    resolvedAccounts.authority.value = context.identity;
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'splSystem',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }
  if (!resolvedAccounts.sysvarInstructions.value) {
    resolvedAccounts.sysvarInstructions.value = publicKey(
      'Sysvar1nstructions1111111111111111111111111'
    );
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getListSubscriptionInstructionDataSerializer().serialize(
    resolvedArgs as ListSubscriptionInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
