/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  publicKey,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  i64,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type SellSubscriptionInstructionAccounts = {
  /** list account */
  list: PublicKey | Pda;
  /** platform account */
  platform: PublicKey | Pda;
  /** user account of buyer */
  user: PublicKey | Pda;
  buyer: Signer;
  seller: PublicKey | Pda;
  /** mint account of chosen token */
  paymentMint: PublicKey | Pda;
  /** buyer's token account of chosen mint */
  buyerTokenAccount: PublicKey | Pda;
  /** seller's token account of chosen mint */
  sellerTokenAccount: PublicKey | Pda;
  mint: PublicKey | Pda;
  tokenAccount: PublicKey | Pda;
  destinationTokenAccount: PublicKey | Pda;
  metadata: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  metadataTokenProgram: PublicKey | Pda;
  sysvarInstructions?: PublicKey | Pda;
  associatedTokenProgram: PublicKey | Pda;
};

// Data.
export type SellSubscriptionInstructionData = {
  discriminator: Array<number>;
  listingStartsAt: bigint;
};

export type SellSubscriptionInstructionDataArgs = {
  listingStartsAt: number | bigint;
};

export function getSellSubscriptionInstructionDataSerializer(): Serializer<
  SellSubscriptionInstructionDataArgs,
  SellSubscriptionInstructionData
> {
  return mapSerializer<
    SellSubscriptionInstructionDataArgs,
    any,
    SellSubscriptionInstructionData
  >(
    struct<SellSubscriptionInstructionData>(
      [
        ['discriminator', array(u8(), { size: 8 })],
        ['listingStartsAt', i64()],
      ],
      { description: 'SellSubscriptionInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [89, 185, 75, 81, 178, 229, 238, 110],
    })
  ) as Serializer<
    SellSubscriptionInstructionDataArgs,
    SellSubscriptionInstructionData
  >;
}

// Args.
export type SellSubscriptionInstructionArgs =
  SellSubscriptionInstructionDataArgs;

// Instruction.
export function sellSubscription(
  context: Pick<Context, 'programs'>,
  input: SellSubscriptionInstructionAccounts & SellSubscriptionInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'dplProtocol',
    'ywpMZZNG3Nx1Bu2deJCcNxzUUoWSm6YwN9r9jCF8art'
  );

  // Accounts.
  const resolvedAccounts: ResolvedAccountsWithIndices = {
    list: { index: 0, isWritable: true, value: input.list ?? null },
    platform: { index: 1, isWritable: false, value: input.platform ?? null },
    user: { index: 2, isWritable: false, value: input.user ?? null },
    buyer: { index: 3, isWritable: true, value: input.buyer ?? null },
    seller: { index: 4, isWritable: false, value: input.seller ?? null },
    paymentMint: {
      index: 5,
      isWritable: false,
      value: input.paymentMint ?? null,
    },
    buyerTokenAccount: {
      index: 6,
      isWritable: true,
      value: input.buyerTokenAccount ?? null,
    },
    sellerTokenAccount: {
      index: 7,
      isWritable: true,
      value: input.sellerTokenAccount ?? null,
    },
    mint: { index: 8, isWritable: false, value: input.mint ?? null },
    tokenAccount: {
      index: 9,
      isWritable: true,
      value: input.tokenAccount ?? null,
    },
    destinationTokenAccount: {
      index: 10,
      isWritable: true,
      value: input.destinationTokenAccount ?? null,
    },
    metadata: { index: 11, isWritable: true, value: input.metadata ?? null },
    systemProgram: {
      index: 12,
      isWritable: false,
      value: input.systemProgram ?? null,
    },
    tokenProgram: {
      index: 13,
      isWritable: false,
      value: input.tokenProgram ?? null,
    },
    metadataTokenProgram: {
      index: 14,
      isWritable: false,
      value: input.metadataTokenProgram ?? null,
    },
    sysvarInstructions: {
      index: 15,
      isWritable: false,
      value: input.sysvarInstructions ?? null,
    },
    associatedTokenProgram: {
      index: 16,
      isWritable: false,
      value: input.associatedTokenProgram ?? null,
    },
  };

  // Arguments.
  const resolvedArgs: SellSubscriptionInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'splSystem',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }
  if (!resolvedAccounts.sysvarInstructions.value) {
    resolvedAccounts.sysvarInstructions.value = publicKey(
      'Sysvar1nstructions1111111111111111111111111'
    );
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getSellSubscriptionInstructionDataSerializer().serialize(
    resolvedArgs as SellSubscriptionInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
